Update README.md
mage-ai/mage-ai pull request #1062
Opened 2022-09-16 00:23 UTC by thomaschung408

FAQs

# Summary

# Tests

cc:

2022-09-16 02:34 UTC, ParthaSarathiChakraborty approved these changes

2022-09-16 03:20 UTC, tommydangerous requested changes

2022-09-16 03:20 UTC, tommydangerous commented on README.md
> +Check out our [FAQ page](https://www.notion.so/mageai/Mage-FAQs-33d93ee65f934ed39568f8a4bc823b39) to find answers to some our most asked questions.
"to some of our most asked questions"

2022-09-16 03:24 UTC, ParthaSarathiChakraborty approved these changes

2022-09-16 16:42 UTC, thomaschung408 reviewed
Changed to "some of our most"

2022-09-20 20:38 UTC, wangxiaoyou1993 approved these changes

2022-09-20 20:45 UTC, merged